### ISSUE TITLE
探讨一下生命周期方法的执行顺序和时机

### ISSUE THREAD

**Issue by chinalwb** [Muran-Hu/Interview#1]
生命周期那个文章里面提到的生命周期方法有：

1. onCreate
2. onStart
3. onResume
4. onPause
5. onStop
6. onDestroy
7. onRestart

想一起讨论下这些方法的执行顺序和时机的问题。

我先提一个：
ActivityA 和 ActivityB 和 ActivityC

他们在manifest中的定义如下：

```
<activity android:name=".MainActivity"> // A
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>


        <activity //  B
            android:name=".C4_SecondActivity"
            android:label="@string/title_activity_c4__second"
            android:theme="@style/Theme.AppCompat.Dialog">
        </activity>

        <activity //  C
            android:name=".C4_ThirdActivity"
            android:label="@string/title_activity_c4__third">
        </activity>
```

我们只关注ActivityA的生命周期。

1. 直接启动ActivityA
    - 这个最简单：onCreate > onStart > onResume
2. 启动ActivityA，然后点击按钮从A中启动B。这个呢？
2. 启动ActivityA，然后点击按钮从A中启动C, 再从C点击后退按钮。 这个呢？
3. 启动ActivityA, 然后点击按钮从A中启动B之后，旋转设备。这个呢？

**Comment by chinalwb** [comment]
注意B的thme是dialog

**Comment by Muran-Hu** [comment]
2. onPause()
由于 B 的 theme 是 dialog，所以启动 B 之后，A 不是完全不可见，所以只执行 onPause(), 不会继续执行后面的方法；
3. onPause() -> onStop() -> onRestart() -> onStart() -> onResume()
C 启动之后，活动栈中有 A 和 C，由于 C 会完全覆盖掉 A，所以会执行 onPause() -> onStop() 两个方法，然后点后退返回 A，此时 C 从栈中去掉，A 在栈顶，所以会执行 onRestart() -> onStart() -> onResume() 方法，A 变为活动状态；
4. onPause() -> onStop() -> onDestroy() -> onCreate() -> onStart() -> onResume() -> onPause()
和 1 类似启动 B 会执行 onPause() 方法，旋转设备， A 和 B 都会销毁，然后重新创建，所以会执行 onStop() -> onDestroy() -> onCreate() -> onStart() -> onResume() -> onPause() 一系列方法，此时 B 处于活动状态；

**Comment by chinalwb** [comment]
完全正确！
